Return LSM6DSOX temperature as float
arduino-libraries/Arduino_LSM6DSOX pull request #19
Opened 2022-07-19 17:15 UTC by daneos

Update temperature API to return temperature with greater precision as `float`.
This addresses [this comment](https://github.com/arduino-libraries/Arduino_LSM6DSOX/issues/7#issuecomment-908078563) in #7.

2022-07-19 17:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_LSM6DSOX?pullRequest=19) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_LSM6DSOX?pullRequest=19) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_LSM6DSOX?pullRequest=19) it.</sub>

2022-08-22 05:08 UTC, aentinger requested changes
Hi :coffee: :wave: You are not obeying the API contract with this change, i..e people who have passed an `int` to `readTemperature` will be in for a surprise. Please add another function, i.e. `readTemperatureFloat` to retrieve the float value (and may it only be a cast to the result of the other function).

2022-08-22 12:34 UTC, daneos commented
I added the requested changes.

I have to admit though, that I was definitely more surprised to learn it was reading the temperature as `int`.
My reasoning is the temperature is usually read as float, the device is perfectly capable of reading it with resolution fit for a float value and the [documentation](https://github.com/arduino-libraries/Arduino_LSM6DSOX/blob/master/docs/readme.md) says `The values returned are signed floats.`

Is there a reason for it to be integer?

2022-08-22 12:40 UTC, aentinger commented
I agree the API could have returned a `float` from the start. The discussion point for me is not what is the better API, but rather how can we honour the API contract established by preceding releases of this library. Now, with an additional function we are not breaking code that is already in use.

2022-08-22 12:40 UTC, aentinger approved these changes
LGTM :+1:

2022-08-22 12:40 UTC, merged